### PR TITLE
Use `bytesize` to calculate content length of unzipped body

### PR DESCRIPTION
**Pull request by rf-**
`length` returns the number of characters, not the number of bytes,
which can cause data to get truncated when the input contains multibyte
characters.

### CODE REVIEW

**Comment by rf-** [comment]
Oops, I meant to PR this onto our fork! Feel free to merge if you want though.

**Comment by rf-** [comment]
I'll clean this up to not have the extraneous merge commit in a minute.

**Comment by andrhamm** [comment]
:+1: would be happy to merge this

**Comment by andrhamm** [comment]
Released in v0.0.3

**Comment by rf-** [comment]
Thanks!

**Pull request merged**
